const ING=[
{name:'Niacinamide',type:'Barrier + Brightening',benefits:'Supports barrier function, helps oil balance and uneven-looking tone.',skin:['oily','combination','normal','dry'],warn:'Usually beginner-friendly; patch test if reactive.'},
{name:'Hyaluronic Acid',type:'Hydration',benefits:'Humectant that helps attract and retain water on the skin surface.',skin:['dry','normal','combination','oily','sensitive'],warn:'Apply on slightly damp skin and follow with moisturizer.'},
{name:'Salicylic Acid',type:'BHA / Exfoliant',benefits:'Helps unclog pores and improve the appearance of acne-prone skin.',skin:['oily','combination'],warn:'Avoid stacking with multiple exfoliants if sensitive.'},
{name:'Retinol',type:'Vitamin A / Active',benefits:'Supports smoother-looking texture and fine-line care over time.',skin:['normal','dry','combination'],warn:'Introduce slowly; avoid combining in the same routine with AHA/BHA in this prototype.'},
{name:'AHA',type:'Exfoliant',benefits:'Helps loosen surface buildup for smoother-looking texture and tone.',skin:['normal','dry','combination'],warn:'Over-exfoliation risk; use less often with sensitive skin.'},
{name:'Ceramides',type:'Barrier Support',benefits:'Helps support the skin barrier and reduce moisture loss.',skin:['dry','sensitive','normal','combination'],warn:'Generally suitable for barrier-focused routines.'},
{name:'Vitamin C',type:'Antioxidant',benefits:'Antioxidant active commonly used for brighter-looking skin and tone.',skin:['normal','oily','combination'],warn:'If irritation occurs, simplify the routine before adding more actives.'},
{name:'Panthenol',type:'Soothing',benefits:'Helps support hydration and a comfortable skin feel.',skin:['sensitive','dry','normal'],warn:'Generally gentle, but individual reactions vary.'}
];
const PRODUCTS=[
{type:'Cleanser',name:'Cloud Reset Gel Cleanser',for:['oily','combination','normal'],conc:['acne','texture'],ings:['salicylic acid','panthenol'],desc:'Low-fuss gel cleanser for a fresh, non-heavy cleanse.'},
{type:'Cleanser',name:'Melt & Mend Cream Cleanser',for:['dry','sensitive','normal'],conc:['redness','dehydration'],ings:['ceramides','panthenol'],desc:'Creamy barrier-first cleanser for dry or reactive profiles.'},
{type:'Serum',name:'Signal 5% Niacinamide',for:['oily','combination','normal','dry'],conc:['acne','dark spots','texture'],ings:['niacinamide'],desc:'A versatile daily serum for oil balance and uneven-looking tone.'},
{type:'Serum',name:'Water Orbit HA + Panthenol',for:['dry','sensitive','normal'],conc:['dehydration','redness'],ings:['hyaluronic acid','panthenol'],desc:'Hydration-focused serum for a plumper, calmer feel.'},
{type:'Serum',name:'Night Shift Retinol',for:['normal','dry','combination'],conc:['aging','texture','dark spots'],ings:['retinol'],desc:'Beginner-style night active for gradual texture and fine-line care.'},
{type:'Moisturizer',name:'Barrier Battery Cream',for:['dry','sensitive','normal'],conc:['dehydration','redness'],ings:['ceramides','panthenol'],desc:'Cushiony moisturizer designed around barrier support.'},
{type:'Moisturizer',name:'Airlock Gel Cream',for:['oily','combination','normal'],conc:['acne','texture'],ings:['niacinamide','panthenol'],desc:'Lightweight gel-cream option for oilier profiles.'},
{type:'Sunscreen',name:'Daylight Shield SPF 50+',for:['oily','combination','normal','dry','sensitive'],conc:['dark spots','aging','redness'],ings:['vitamin c'],desc:'Daily broad-spectrum sunscreen placeholder for the prototype.'}
];
let state=JSON.parse(localStorage.getItem('dermoraState')||'null')||{user:null,profile:null,users:[{name:'Demo User',email:'user@demo.com',password:'1234',role:'user'}]};
let authType='login';
function save(){localStorage.setItem('dermoraState',JSON.stringify(state))}
function go(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'});}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function openAuth(){document.getElementById('authModal').classList.add('show');authMode('login')}
function closeAuth(){document.getElementById('authModal').classList.remove('show')}
function authMode(m){authType=m;['loginTab','registerTab','adminTab'].forEach(x=>document.getElementById(x).classList.remove('on'));document.getElementById(m==='login'?'loginTab':m==='register'?'registerTab':'adminTab').classList.add('on');document.getElementById('authTitle').textContent=m==='register'?'Create account':m==='admin'?'Admin login':'Login';document.getElementById('authName').classList.toggle('hidden',m!=='register');document.getElementById('authSubmit').textContent=m==='register'?'Register':'Login';document.getElementById('authHint').textContent=m==='admin'?'Demo admin: admin@dermora.com / admin123':'Demo user: user@demo.com / 1234'}
function submitAuth(){let n=document.getElementById('authName').value.trim(),e=document.getElementById('authEmail').value.trim().toLowerCase(),p=document.getElementById('authPass').value;if(authType==='register'){if(!n||!e||p.length<4)return toast('Enter name, email and 4+ character password.');if(state.users.some(u=>u.email===e))return toast('Email already registered.');state.users.push({name:n,email:e,password:p,role:'user'});state.user={name:n,email:e,role:'user'};save();closeAuth();refresh();toast('Account created!')}else if(authType==='admin'){if(e!=='admin@dermora.com'||p!=='admin123')return toast('Invalid demo admin credentials.');state.user={name:'Administrator',email:e,role:'admin'};save();closeAuth();refresh();toast('Admin mode enabled.')}else{const u=state.users.find(x=>x.email===e&&x.password===p);if(!u)return toast('Invalid login details.');state.user={name:u.name,email:u.email,role:u.role};save();closeAuth();refresh();toast('Welcome back, '+u.name+'!')}}
function logout(){state.user=null;save();refresh();toast('Logged out.')}
function refresh(){const u=state.user;document.getElementById('userChip').textContent=u?u.name:'Guest';document.getElementById('authBtn').classList.toggle('hidden',!!u);document.getElementById('logoutBtn').classList.toggle('hidden',!u);document.querySelector('.admin').classList.toggle('show',u?.role==='admin');if(u?.role==='admin'){renderUsers()}renderDashboard();}
function learnTab(tab,el){document.querySelectorAll('#learn .pill').forEach(x=>x.classList.remove('active'));el.classList.add('active');const data={types:[['Dry','Often feels tight; focus on gentle cleansing and barrier support.','💧'],['Oily','Often shows more shine; lightweight hydration and pore care can help.','🫧'],['Combination','Different zones may behave differently; balance matters.','◐'],['Sensitive','Prioritise simplicity, gentle formulas and slow introductions.','🌿'],['Normal','Generally balanced; maintain consistency and avoid unnecessary complexity.','◉']],concerns:[['Acne','Focus on consistent cleansing, non-heavy hydration and carefully introduced actives.','◎'],['Dark spots','Daily sunscreen is foundational; brightening actives can complement it.','✦'],['Dehydration','Add humectants and barrier-supporting moisturizer while avoiding over-cleansing.','💦'],['Texture','Gentle exfoliation or retinoid-style care may help, introduced gradually.','▦'],['Redness','Keep the routine simple and barrier-focused; reduce potential irritants.','🌱']],basics:[['Cleanse','Remove sunscreen, makeup and buildup without aggressively stripping the skin.','01'],['Moisturize','Support the barrier and reduce moisture loss with a consistent moisturizer.','02'],['Protect','Use sunscreen in the daytime as a core prevention step.','03']],routine:[['Morning','Cleanser → serum (optional) → moisturizer → sunscreen.','☀'],['Night','Cleanser → treatment (optional) → moisturizer.','☾'],['Golden rule','Add one new active at a time and monitor how your skin responds.','✦']]};document.getElementById('learnGrid').innerHTML=data[tab].map(x=>`<div class="card learn-card"><div class="icon">${x[2]}</div><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}
function renderIngredients(){let q=document.getElementById('ingredientSearch').value.toLowerCase();let arr=ING.filter(x=>(x.name+' '+x.type+' '+x.benefits).toLowerCase().includes(q));document.getElementById('ingredientGrid').innerHTML=arr.map(x=>`<div class="card ingredient-card"><span class="tag cool">${x.type}</span><h3>${x.name}</h3><p>${x.benefits}</p><b>Suitable:</b><div>${x.skin.map(s=>`<span class="tag">${s}</span>`).join('')}</div><div class="warning" style="margin-top:12px">⚠ ${x.warn}</div></div>`).join('')||'<div class="card">No ingredient found.</div>'}
function getConcerns(){return [...document.querySelectorAll('#concernChecks input:checked')].map(x=>x.value)}
function analyze(){const type=document.getElementById('skinType').value, concerns=getConcerns(), sensitivity=document.getElementById('sensitivity').value,goal=document.getElementById('goal').value;state.profile={type,concerns,sensitivity,goal,updated:new Date().toLocaleString()};save();renderDashboard();renderRecommendations();renderAlerts();toast('Profile analysed and saved.');go('dashboard')}
function scoreProduct(p){let s=55;if(p.for.includes(state.profile?.type))s+=20;const cs=state.profile?.concerns||[];s+=Math.min(20,cs.filter(c=>p.conc.includes(c)).length*8);if(state.profile?.sensitivity==='high'&&p.ings.some(i=>['retinol','salicylic acid','aha'].includes(i)))s-=18;if(state.profile?.goal==='hydration'&&p.ings.includes('hyaluronic acid'))s+=8;if(state.profile?.goal==='brightening'&&p.ings.includes('niacinamide'))s+=8;return Math.max(35,Math.min(99,s))}
function renderRecommendations(){const arr=[...PRODUCTS].sort((a,b)=>scoreProduct(b)-scoreProduct(a));document.getElementById('productGrid').innerHTML=arr.slice(0,4).map(p=>`<div class="card product recommend"><span class="producttype">${p.type}</span><span class="match">${scoreProduct(p)}%</span><h3>${p.name}</h3><p>${p.desc}</p><div>${p.ings.map(i=>`<span class="tag">${i}</span>`).join('')}</div></div>`).join('')}
function renderDashboard(){const p=state.profile;if(!p){document.getElementById('dashProfile').textContent='Not analysed yet';document.getElementById('dashScore').textContent='—';document.getElementById('dashBar').style.width='0';document.getElementById('dashConcerns').innerHTML='<span class="tag">No profile yet</span>';document.getElementById('dashSensitivity').textContent='—';return}let base=68+(p.concerns.length*4)+(p.sensitivity==='low'?10:p.sensitivity==='medium'?5:0);base=Math.min(96,base);document.getElementById('dashProfile').textContent=p.type[0].toUpperCase()+p.type.slice(1)+' skin · '+p.goal;document.getElementById('dashScore').textContent=base+'%';document.getElementById('dashBar').style.width=base+'%';document.getElementById('dashConcerns').innerHTML=(p.concerns.length?p.concerns:['Balanced / maintenance']).map(c=>`<span class="tag">${c}</span>`).join('');document.getElementById('dashSensitivity').textContent=p.sensitivity[0].toUpperCase()+p.sensitivity.slice(1);document.getElementById('dashAlert').textContent=p.sensitivity==='high'?'High sensitivity: keep actives minimal and introduce slowly.':'Profile active: use the alerts below before layering treatments.';renderRecommendations();renderAlerts()}
function renderAlerts(){const p=state.profile;const arr=[];if(!p){arr.push(['yellow','Complete Skin Analysis','Your smart alerts activate after you create a profile.']);}else{if(p.sensitivity==='high')arr.push(['red','Sensitive-skin warning','Keep exfoliating acids and retinoids minimal. Patch test and simplify if irritation occurs.']);if(p.concerns.includes('acne'))arr.push(['blue','Acne-care note','Avoid piling multiple strong exfoliants just because a product targets pores.']);arr.push(['yellow','Ingredient conflict','This prototype flags Retinol + AHA/BHA as a same-routine conflict.']);arr.push(['red','Over-exfoliation','If your routine already contains AHA/BHA, avoid adding another exfoliating product without reducing frequency.']);}document.getElementById('alertGrid').innerHTML=arr.map(a=>`<div class="alert ${a[0]}"><b>${a[1]}</b><p>${a[2]}</p></div>`).join('');renderRoutine()}
function renderRoutine(){const p=state.profile||{type:'normal',sensitivity:'low',goal:'barrier'};let treatment=p.goal==='antiaging'?'Night Shift Retinol':p.goal==='acne'?'Signal 5% Niacinamide':p.goal==='brightening'?'Signal 5% Niacinamide':'Water Orbit HA + Panthenol';if(p.sensitivity==='high')treatment='Water Orbit HA + Panthenol';document.getElementById('amRoutine').innerHTML=['Gentle cleanse','Hydrating / targeted serum','Moisturizer','SPF 50+'].map((x,i)=>`<div class="step"><span class="num">${i+1}</span><div>${x}</div></div>`).join('');document.getElementById('pmRoutine').innerHTML=['Cleanse',''+treatment,'Barrier moisturizer'].map((x,i)=>`<div class="step"><span class="num">${i+1}</span><div>${x}</div></div>`).join('')}
function renderUsers(){document.getElementById('userCount').textContent=state.users.length;document.getElementById('userList').innerHTML=state.users.map((u,i)=>`<div class="userrow"><div><b>${u.name}</b><br><small>${u.email} · ${u.role}</small></div><button class="btn outline" onclick="deleteUser(${i})" ${u.role==='admin'?'disabled':''}>Delete</button></div>`).join('')}
function deleteUser(i){if(confirm('Delete this local demo user?')){state.users.splice(i,1);save();renderUsers();toast('User deleted.')}}
function toggleChat(){document.getElementById('chatbox').classList.toggle('open');if(document.getElementById('chatbox').classList.contains('open'))setTimeout(()=>document.getElementById('chatInput').focus(),100)}
function botReply(q){q=q.toLowerCase();const p=state.profile;if(/retinol.*(aha|bha)|(aha|bha).*retinol/.test(q))return'⚠️ In this prototype, Retinol + AHA/BHA is flagged as a same-routine conflict. Try separating them and keep frequency low.';if(q.includes('niacinamide'))return'Niacinamide is a versatile barrier-supporting ingredient. In DERMORA it is matched especially with oil balance, acne, dark spots and texture concerns.';if(q.includes('sunscreen')||q.includes('spf'))return'Sunscreen is the final morning step. For this prototype, the recommended sunscreen is Daylight Shield SPF 50+.';if(q.includes('routine'))return'Your default routine is cleanse → treatment/serum → moisturizer at night, and cleanse → serum → moisturizer → SPF in the morning.';if(q.includes('profile')||q.includes('skin type'))return p?`Your current profile is ${p.type} skin, ${p.sensitivity} sensitivity, concerns: ${p.concerns.join(', ')||'none selected'}, goal: ${p.goal}.`:'You have not completed Skin Analysis yet.';if(q.includes('acne'))return'For acne-prone profiles, DERMORA prioritises gentle cleansing, non-heavy hydration and carefully introduced pore-care ingredients such as salicylic acid.';if(q.includes('ingredient'))return'Try asking: “What does retinol do?”, “Is niacinamide suitable for oily skin?”, or “Can I use retinol with AHA?”';if(q.includes('product'))return'Product recommendations are scored from skin type, selected concerns, sensitivity and goal. Run Skin Analysis first for personalised results.';if(q.includes('sensitive'))return'For sensitive skin, keep the routine simple, introduce one active at a time and watch for irritation. High sensitivity triggers extra warnings in this prototype.';return'I can help with skincare ingredients, concerns, routines, products, your profile and ingredient combinations. Try asking a more specific skincare question.'}
function sendChat(){const input=document.getElementById('chatInput'),q=input.value.trim();if(!q)return;const m=document.getElementById('messages');m.innerHTML+=`<div class="msg me">${escapeHtml(q)}</div>`;input.value='';setTimeout(()=>{m.innerHTML+=`<div class="msg bot">${botReply(q)}</div>`;m.scrollTop=m.scrollHeight},250)}function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
learnTab('types',document.querySelector('#learn .pill'));renderIngredients();renderRoutine();refresh();
